name: Android CI

on:
  push:
    branches: [ "main", "principal" ]
  pull_request:
    branches: [ "main", "principal" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools
            platforms;android-33
            build-tools;33.0.2

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Clean
        run: ./gradlew clean --no-daemon

      - name: Build Debug APK
        # força construir o app debug do módulo "app"
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon

      - name: Show outputs (for debugging)
        # Mostra qualquer APK gerado e onde ele está
        run: |
          echo "=== Procurando APKs em app/build ==="
          find app/build -type f -name "*.apk" -printf "%p\n" || true
          echo "=== FIM ==="

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          # cobre caminhos como app/build/outputs/apk/debug/app-debug.apk,
          # split APKs, e variações novas do AGP
          path: |
            app/build/outputs/**/*.apk
            **/build/outputs/**/*.apk
          if-no-files-found: error
