name: Android CI

on:
  push:
    branches: [ "main", "principal" ]
  pull_request:
    branches: [ "main", "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Clean
        run: ./gradlew clean

      - name: Build Release APK
        run: ./gradlew :app:assembleRelease --no-daemon --stacktrace

      # Se o build de release falhar, tenta gerar o debug para garantir artefato
      - name: Build Debug APK (fallback)
        if: ${{ failure() }}
        run: ./gradlew :app:assembleDebug --no-daemon --stacktrace

      # Faz upload de qualquer APK gerado (release e/ou debug)
      - name: Upload APK(s)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: EcoImpact-APK
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
