name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Clean
        run: ./gradlew clean

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace

      # Apenas para depuração: mostra onde o Gradle gerou artefatos
      - name: Show outputs
        run: |
          echo "=== app/build/outputs ==="
          ls -R app/build/outputs || true
          echo "=== APKs encontrados ==="
          find app/build -type f -name "*.apk" -maxdepth 6 || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EcoImpact-APK
          path: |
            app/build/outputs/**/*.apk
          if-no-files-found: error
          retention-days: 7
