name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Clean
        run: ./gradlew clean

      # 👇 força compilar o módulo "app" no variant Debug
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace

      # (opcional) lista onde os arquivos foram gerados para debug
      - name: Show outputs
        run: |
          echo "== app/build/outputs =="
          ls -R app/build/outputs || true

      # 👇 amplia o glob para qualquer pasta de outputs que contenha APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EcoImpact-APK
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/*.apk
            **/build/outputs/apk/**/*.apk
          if-no-files-found: error
          retention-days: 7
